-- rrt_planner
RRT_STOP_DIST = 0.5;
RRT_W_A = 1.0;
RRT_W_C = 1.0;
RRT_CLEARANCE = 0.3;
RRT_SEARCH_BUFFER = 4; -- 2m dist travelled
RRT_LOCAL_HORIZON = 2.0

-- planner
CIRCLE_RADIUS = 2.0;
STOP_DIST = 0.7;
SEARCH_BUFFER = 5;
CLEARANCE = 0.3;
HEURISTIC_INFLATION = 1.05;

-- scoring function
W_CLEARANCE = 0.1;
W_GOAL_DIST = 4.0;
MAX_LOCAL_GOAL_DIST = CIRCLE_RADIUS;
